#!/usr/bin/env bash

PROJECT_ID=$(gcloud info --format='value(config.project)')

GKE_CLUSTER=spin-demo
ZONE=us-west1-b

if [ -f bucket.txt ]; then
  BUCKET_NAME=$(cat bucket.txt)
else
  BUCKET_NAME="spin-gcs-bucket-$(cat /dev/urandom | tr -dc 'a-z0-9' | fold -w 20 | head -n 1)-$(date +"%s")"
  echo $BUCKET_NAME > bucket.txt
fi

BUCKET_URI="gs://$BUCKET_NAME"

SERVICE_ACCOUNT_NAME="spin-project-account"
SERVICE_ACCOUNT_DEST="~/.gcp/gce-account.json"

GCS_TOPIC="spin-gcs-topic"
GCS_SUB="spin-gcs-sub"
SPIN_GCS_ACCOUNT="my-gcs-account"
SPIN_PUB_SUB="my-gcp-pub-sub"
